all:
	g++-4.8 problem.cpp -o problem -std=c++0x -Wpedantic -Wextra -Wall -Warray-bounds -Wmaybe-uninitialized -Wmaybe-uninitialized -Wuninitialized -Werror && g++-4.8 gen_tests.cpp -o gen_test -std=c++0x -Wpedantic -Wextra -Wall -Warray-bounds -Wmaybe-uninitialized -Wmaybe-uninitialized -Wuninitialized -Werror
test:
	./make_test.sh


